<?php

namespace BRM\JamsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JamRepository extends EntityRepository
{
}
