

security:
    providers:
        main:
            id: fos_user.user_provider.username
           
    encoders:
        OpenJams\UserBundle\Entity\User: sha512
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            pattern: ^/
            security: true
            provider: main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /
            remember_me:
                key: %secret%
                
                


