parameters:
#    open_jams_user.example.class: OpenJams\UserBundle\Example

services:
#    open_jams_user.example:
#        class: %open_jams_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
